CREATE DATABASE IF NOT EXISTS booknest_auth;
CREATE DATABASE IF NOT EXISTS booknest_books;
CREATE DATABASE IF NOT EXISTS booknest_cart;
CREATE DATABASE IF NOT EXISTS booknest_orders;
CREATE DATABASE IF NOT EXISTS booknest_wallet;
CREATE DATABASE IF NOT EXISTS booknest_review;
CREATE DATABASE IF NOT EXISTS booknest_wishlist;
CREATE DATABASE IF NOT EXISTS booknest_notification;